name: CI/CD

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.X

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pylint
        run: make lint
        continue-on-error: true

      - name: Run pytest
        run: |
          export PYTHONPATH="$PWD/src"
          make code_test

  deploy:
    runs-on: ubuntu-latest

    needs: build_and_test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.X

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Launch mlflow
        run: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts --host 0.0.0.0 -p 1234 &

      - name: Deploy designated mlflow model to production
        run: |
          export PYTHONPATH="$PWD/src"
          python ./src/model/deploy.py --run_type=PROD
