name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration Testing"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.X

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Launch mlflow
        run: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts --host 0.0.0.0 -p 1234

      - name: Deploy designated mlflow model to production
        run: |
          export PYTHONPATH="$PWD/src"
          python ./src/model/deploy.py --run_type=PROD
